image: tpa3/php:7.2.4

before_script:
  - mkdir -p ./data/composercache
  - composer config cache-files-dir ./data/composercache
  - composer config --global discard-changes true
  - composer install --dev --no-suggest

cache:
  #unique cache per each jobname and branch
  key: "$CI_PROJECT_ID-$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
  paths:
    - ./vendor
    - ./data/composercache

test:php7.2:
  script:
    - phpunit --no-coverage --colors=never
    - composer exec -vv phpcs

test:php5.6:
  image: tpa3/php:5.6
  script:
    - phpunit --no-coverage --colors=never
