language: php
php:
  - '5.6'
  - '7.1'
  - '7.2'

before_script:
  - composer install --prefer-source --no-interaction --dev
  - export PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

script:
  - phpunit
  - phpcs --standard=phpcs.xml "$TRAVIS_BUILD_DIR/src"
  
notifications:
    on_success: never
    on_failure: always
